### ISSUE TITLE
can't creat a socket with TYPE=CAT_SOCKET_TYPE_FLAG_STREAM

### ISSUE THREAD

**Issue by xxyyboy** [libcat/libcat#18]
https://github.com/libcat/libcat/blob/a0dc63ad2ec67019367141b531702d21000b0ae7/src/cat_socket.c#L796

**Comment by twose** [comment]
`type` should be one of `cat_socket_type_t`, e.g `TCP`, `UDP`, and so on... But not `cat_socket_type_flag_t`.

**Comment by xxyyboy** [comment]
thanks
