### ISSUE TITLE
怎么用 已知的fd 创建一个 cat_socket_t 

### ISSUE THREAD

**Issue by xxyyboy** [libcat/libcat#19]
使用这个函数，始终会失败 cat_socket_open_os_fd
fd 为dup出来的一个fd
cat_socket_open_os_fd(&myserver, CAT_SOCKET_TYPE_TCP,fd) != NULL ? cat_true : cat_false;

cat_socket_t *connection = cat_socket_create(NULL, cat_socket_get_simple_type(&myserver));

if (!cat_socket_accept(&myserver, connection))

cat_socket_accept 会返回0

帮助文档比较少，找不到帮助材料，麻烦了

**Comment by xxyyboy** [comment]
ret = cat_socket_open_os_fd(&myserver, CAT_SOCKET_TYPE_TCP4,fd) != NULL ? cat_true : cat_false;
	ret = cat_socket_bind_to(&myserver, CAT_STRL("0.0.0.0"), 9000);
	ret = cat_socket_listen(&myserver, 1024);
        成功了，需要重新bind  listen

**Comment by twose** [comment]
对的，不过为什么会有这样的需求，这里的设计可能会改，目前的做法有点问题，后面会把 create 的 open 分开成两个函数而不是合成一个 (和 libuv 保持一致)

**Comment by xxyyboy** [comment]
感谢回复。
这里是在以前的代码里面尝试改下，以前的代码只改了部分逻辑，代码里面业务逻辑依赖太多，先试试效果。
后面再一步一步改下。
顺祝春节愉快

**Comment by twose** [comment]
https://github.com/libcat/libcat/commit/b422778df0395d6f26d1794b6639e3e8693b98da

已经拆成两步，可以看 tests 改变的部分作为参考。
讲道理不需要重新 bind ，但肯定需要重新 listen 来注册 libuv 的事件，目前没有一个通用的去判断 socket 是否处于监听状态的方式，因此没办法屏蔽掉这一点。

**Comment by xxyyboy** [comment]
收到，感谢
